services:
  frontend:
    container_name: frontend
    image: node:14.15-buster-slim
    working_dir: /app
    stdin_open: true
    tty: true
    labels:
      traefik.http.routers.ah_frontend.rule: Host(`${DOMAIN}`)
      traefik.http.routers.ah_frontend.entrypoints: websecure
      traefik.http.routers.ah_frontend.tls.certresolver: cfdnsresolver
      traefik.http.routers.ah_frontend.tls.domains[0].main: ${DOMAIN}
      traefik.http.routers.ah_frontend.tls.domains[0].sans: www.${DOMAIN}
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    external:
      name: traefik
